### PR TITLE
Update docker-compose.yml

### PR DESCRIPTION
**Pull request by schlpbch**
- Pull php image instead of building it
- Use latest version of MySQL

### CODE REVIEW

**Comment by marvincaspar** [comment]
Pulling PHP image instead of building it does not work. Magento requires some php extensions you have to add to your image. We also add xdebug for the development environment.

**Comment by schlpbch** [comment]
Which php extensions are we talking about? I'm sure there's a reasonable image available :-)

**Comment by andreaskoch** [comment]
Your idea is good. We did it this way to make the project as hackable as possible. But for getting started a pre-built docker image is much better (faster).

I will try to set up an automatically built docker image image from the customized PHP container in the [config/php/image/Dockerfile](https://github.com/arvatoSCM/dockerize-magento2/blob/develop/config/php/image/Dockerfile) image definition.

Unfortunately Docker Hub currently for some strange reason does not support to to created automated docker images from repositories that are owned by an organization. I only get to see the repositories that I directly own.

... I will try a workaround. I will let you know once it is ready.

**Comment by andreaskoch** [comment]
I have just created an auto-build docker image [arvato/magento2-php](https://hub.docker.com/r/arvato/magento2-php/).

If you reference the `arvato/magento2-php:latest` image in the docker-compose.yml I can merge your pull request ([docker-compose.yml:Line 20](https://github.com/arvatoSCM/dockerize-magento2/pull/8/commits/e80617b3abab92b067f3ac7ce50d8cdefe0b6e12#diff-4e5e90c6228fd48698d074241c2ba760R20)).

screenshot-2016-11-05-001-arvato-magento2-php - docker hub - google chrome

For the MySQL image I would like to ask you to change the reference to mysql:5.7 instead of latest ([docker-compose.yml:Line 43](https://github.com/arvatoSCM/dockerize-magento2/pull/8/commits/e80617b3abab92b067f3ac7ce50d8cdefe0b6e12#diff-4e5e90c6228fd48698d074241c2ba760R43)) because a future version of MySQL might break some things and we like to keep a tight grip on our version numbers.

Or even better, create a separate pull request for the MySQL version upgrade. So we don't mix multiple changes in one commit.

**Comment by schlpbch** [comment]
Great work, will split the pull request.

I agree with the exact versioning, what about extending it to all the images? I can create a patch.

I would also suggest not sharing the host file systems between the containers. What's your take on that?

**Comment by schlpbch** [comment]
Dear all

It seems as if the build is broken. Can you please check?

Thanks in advance
-as

[image: pasted1]

Andreas Koch notifications@github.com schrieb am Sa., 5. Nov. 2016 um
19:24 Uhr:

**Pull request closed without merging**
